apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: vti-sonlh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 084375555299.dkr.ecr.us-east-1.amazonaws.com/final-asignment-app-repo:latest
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: "identifier-db.cfwoy6guyqmd.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "db_name"
        - name: AWS_REGION
          value: "us-east-1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"