apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: vti-sonlh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: ssm-service-account
      containers:
      - name: backend
        # image: 084375555299.dkr.ecr.us-east-1.amazonaws.com/final-asignment-app-repo:latest
        image: __IMAGE__
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: __DB_HOST__
        - name: DB_NAME
          value: __DB_NAME__
        - name: AWS_REGION
          value: __AWS_REGION__
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"